-- A representation of a lambdaQ program in the shape of an abstract syntax tree
-- will be generated here. Subsequently the abstract syntax tree is converted
-- to an intermediate abstract syntax tree with a simpler syntax to make it easier
-- to process by the semantic analyser, type checker and the code generator.

module Backend.ASTConverter where

import Backend.IAST (Program, mapFunction, reverseMapFunction )
import Frontend.LambdaQ.Par ( myLexer, pProgram )
import Frontend.LambdaQ.Print ( printTree )
import qualified Frontend.LambdaQ.Abs as GeneratedAbSyntax
import GHC.Err ( errorWithoutStackTrace )

parse :: String -> Program
parse str = case pProgram (myLexer str) of
   Left str -> errorWithoutStackTrace str
   Right p -> mapProgram p

-- an AST program is just a list of functions
mapProgram :: GeneratedAbSyntax.Program -> Program
mapProgram (GeneratedAbSyntax.ProgDef funs) = map mapFunction funs

-- an IAST program is also just a list of functions
reverseMapProgram :: Program -> GeneratedAbSyntax.Program
reverseMapProgram = GeneratedAbSyntax.ProgDef . map reverseMapFunction

-- the prinTree function is generated by the BNF converter
parseAndPrintTreeFromString :: String -> String
parseAndPrintTreeFromString str = case pProgram (myLexer str) of
    Left str -> errorWithoutStackTrace str
    Right prog -> printTree prog

parseAndPrintTreeFromFile :: FilePath -> IO String
parseAndPrintTreeFromFile path = parseAndPrintTreeFromString <$> readFile path
