-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language lambdaQ.

module LambdaQ.Abs where

import Prelude (Double, Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Int, Maybe(..)
  )

data Type
    = TypeBit
    | TypeQbit
    | TypeUnit
    | TypeExp Type
    | TypeTens Type Type
    | TypeFunc Type Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Angle = AAngl Double
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlState
    = CStateZero
    | CStateOne
    | CStatePlus
    | CStateMinus
    | CStateIPlus
    | CStateIMinus
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Control = CCtrl Integer ControlState
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Gate
    = GH [Control]
    | GX [Control]
    | GY [Control]
    | GZ [Control]
    | GI [Control]
    | GXRt [Control]
    | GXRtDag [Control]
    | GYRt [Control]
    | GYRtDag [Control]
    | GZRt [Control]
    | GZRtDag [Control]
    | GS [Control]
    | GSDag [Control]
    | GT [Control]
    | GTDag [Control]
    | GV [Control]
    | GVDag [Control]
    | Gh [Control]
    | GhDag [Control]
    | GRxTheta Angle [Control]
    | GRyTheta Angle [Control]
    | GRzTheta Angle [Control]
    | GU1 Angle [Control]
    | GU2 Angle Angle [Control]
    | GU3 Angle Angle Angle [Control]
    | GSWP [Control]
    | GSQRTSWP [Control]
    | GISWP [Control]
    | GFSWP [Control]
    | GSWPRt [Control]
    | GSWPRtDag [Control]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LetVariable = LVar Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Tuple = Tup Term [Term]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Bit = BBit Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term
    = TVar Var
    | TBit Bit
    | TGate Gate
    | TTup Tuple
    | TUnit
    | TApp Term Term
    | TIfEl Term Term Term
    | TLet LetVariable [LetVariable] Term Term
    | TCase Term Var Term Var Term
    | TLmbd Lambda FunVariable Type Term
    | TDollr Term Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Arg = FunArg Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Function = FunDef Var [Arg] Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunDeclaration = FunDecl FunVariable Type Function
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Program = ProgDef [FunDeclaration]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Var = Var ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype FunVariable = FunVariable ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Lambda = Lambda ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Var where
  hasPosition (Var (p, _)) = C.Just p

instance HasPosition FunVariable where
  hasPosition (FunVariable (p, _)) = C.Just p

instance HasPosition Lambda where
  hasPosition (Lambda (p, _)) = C.Just p

