-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language LambdaQ.

module Frontend.LambdaQ.Abs where

import Prelude (Double, Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Int, Maybe(..)
  )
import qualified Data.String

data Program = ProgDef [FunctionDeclaration]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
    = TypeBit
    | TypeQbit
    | TypeState
    | TypeUnitary
    | TypeUnit
    | TypeNonLinear Type
    | TypeExp Type Integer
    | TypeTensorProd Type Type
    | TypeSum Type Type
    | TypeFunction Type Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Angle = Angle Double
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data BasisState
    = BasisStateZero
    | BasisStateOne
    | BasisStatePlus
    | BasisStateMinus
    | BasisStatePlusI
    | BasisStateMinusI
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Bit = BitValue Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Gate
    = GateH
    | GateX
    | GateY
    | GateZ
    | GateID
    | GateXRoot Integer
    | GateXRootDag Integer
    | GateYRoot Integer
    | GateYRootDag Integer
    | GateZRoot Integer
    | GateZRootDag Integer
    | GateS
    | GateSDag
    | GateT
    | GateTDag
    | GateSqrtX
    | GateSqrtXDag
    | GateSqrtY
    | GateSqrtYDag
    | GateRxTheta Angle
    | GateRyTheta Angle
    | GateRzTheta Angle
    | GateU1 Angle
    | GateU2 Angle Angle
    | GateU3 Angle Angle Angle
    | GateSwp
    | GateSqrtSwp
    | GateSqrtSwpDag
    | GateISwp
    | GateFSwp
    | GateSwpTheta Angle
    | GateSwpRt Integer
    | GateSwpRtDag Integer
    | GateQft Integer
    | GateQftDag Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlBasisState = CtrlBasisState BasisState
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlBasisStates = CtrlBasisStates BasisState [BasisState]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlBit = CtrlBit Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlBits = CtrlBits Integer [Integer]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Tuple = Tupl Term [Term]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlTerm = CtrlTerm Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ControlTerms = CtrlTerms Term [Term]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term
    = TermIfElse Term Term Term
    | TermLetSingle LetVariable Term Term
    | TermLetMultiple LetVariable [LetVariable] Term Term
    | TermLetSugarSingle LetVariable Term Term
    | TermLetSugarMultiple LetVariable [LetVariable] Term Term
    | TermCase Term CaseExpression [CaseExpression]
    | TermLambda Lambda Var Type Term
    | TermQuantumCtrlGate ControlTerm ControlBasisState
    | TermQuantumCtrlsGate ControlTerms ControlBasisStates
    | TermClassicCtrlGate ControlTerm ControlBit
    | TermClassicCtrlsGate ControlTerms ControlBits
    | TermApply Term Term
    | TermDollar Term Term
    | TermCompose Term Term
    | TermVariable Var
    | TermBasisState BasisState
    | TermGate Gate
    | TermTuple Tuple
    | TermBit Bit
    | TermUnit
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LetVariable = LetVar Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data CaseExpression = CaseExp Term Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Arg = FunArg Var
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunctionDefinition = FunDef Var [Arg] Term
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunctionType = FunType Var Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FunctionDeclaration = FunDecl FunctionType FunctionDefinition
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Var = Var ((C.Int, C.Int), String)
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Lambda = Lambda String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Var where
  hasPosition (Var (p, _)) = C.Just p

