-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module LambdaQ.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified LambdaQ.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVar :: LambdaQ.Abs.Var -> Result
transVar x = case x of
  LambdaQ.Abs.Var string -> failure x

transFunVariable :: LambdaQ.Abs.FunVariable -> Result
transFunVariable x = case x of
  LambdaQ.Abs.FunVariable string -> failure x

transLambda :: LambdaQ.Abs.Lambda -> Result
transLambda x = case x of
  LambdaQ.Abs.Lambda string -> failure x

transType :: LambdaQ.Abs.Type -> Result
transType x = case x of
  LambdaQ.Abs.TypeBit -> failure x
  LambdaQ.Abs.TypeQbit -> failure x
  LambdaQ.Abs.TypeUnit -> failure x
  LambdaQ.Abs.TypeExp type_ -> failure x
  LambdaQ.Abs.TypeTens type_1 type_2 -> failure x
  LambdaQ.Abs.TypeFunc type_1 type_2 -> failure x

transAngle :: LambdaQ.Abs.Angle -> Result
transAngle x = case x of
  LambdaQ.Abs.AAngl double -> failure x

transControlState :: LambdaQ.Abs.ControlState -> Result
transControlState x = case x of
  LambdaQ.Abs.CStateZero -> failure x
  LambdaQ.Abs.CStateOne -> failure x
  LambdaQ.Abs.CStatePlus -> failure x
  LambdaQ.Abs.CStateMinus -> failure x
  LambdaQ.Abs.CStateIPlus -> failure x
  LambdaQ.Abs.CStateIMinus -> failure x

transControl :: LambdaQ.Abs.Control -> Result
transControl x = case x of
  LambdaQ.Abs.CCtrl integer controlstate -> failure x

transGate :: LambdaQ.Abs.Gate -> Result
transGate x = case x of
  LambdaQ.Abs.GH controls -> failure x
  LambdaQ.Abs.GX controls -> failure x
  LambdaQ.Abs.GY controls -> failure x
  LambdaQ.Abs.GZ controls -> failure x
  LambdaQ.Abs.GI controls -> failure x
  LambdaQ.Abs.GXRt controls -> failure x
  LambdaQ.Abs.GXRtDag controls -> failure x
  LambdaQ.Abs.GYRt controls -> failure x
  LambdaQ.Abs.GYRtDag controls -> failure x
  LambdaQ.Abs.GZRt controls -> failure x
  LambdaQ.Abs.GZRtDag controls -> failure x
  LambdaQ.Abs.GS controls -> failure x
  LambdaQ.Abs.GSDag controls -> failure x
  LambdaQ.Abs.GT controls -> failure x
  LambdaQ.Abs.GTDag controls -> failure x
  LambdaQ.Abs.GV controls -> failure x
  LambdaQ.Abs.GVDag controls -> failure x
  LambdaQ.Abs.Gh controls -> failure x
  LambdaQ.Abs.GhDag controls -> failure x
  LambdaQ.Abs.GRxTheta angle controls -> failure x
  LambdaQ.Abs.GRyTheta angle controls -> failure x
  LambdaQ.Abs.GRzTheta angle controls -> failure x
  LambdaQ.Abs.GU1 angle controls -> failure x
  LambdaQ.Abs.GU2 angle1 angle2 controls -> failure x
  LambdaQ.Abs.GU3 angle1 angle2 angle3 controls -> failure x
  LambdaQ.Abs.GSWP controls -> failure x
  LambdaQ.Abs.GSQRTSWP controls -> failure x
  LambdaQ.Abs.GISWP controls -> failure x
  LambdaQ.Abs.GFSWP controls -> failure x
  LambdaQ.Abs.GSWPRt controls -> failure x
  LambdaQ.Abs.GSWPRtDag controls -> failure x

transLetVariable :: LambdaQ.Abs.LetVariable -> Result
transLetVariable x = case x of
  LambdaQ.Abs.LVar var -> failure x

transTuple :: LambdaQ.Abs.Tuple -> Result
transTuple x = case x of
  LambdaQ.Abs.Tup term terms -> failure x

transBit :: LambdaQ.Abs.Bit -> Result
transBit x = case x of
  LambdaQ.Abs.BBit integer -> failure x

transTerm :: LambdaQ.Abs.Term -> Result
transTerm x = case x of
  LambdaQ.Abs.TVar var -> failure x
  LambdaQ.Abs.TBit bit -> failure x
  LambdaQ.Abs.TGate gate -> failure x
  LambdaQ.Abs.TTup tuple -> failure x
  LambdaQ.Abs.TUnit -> failure x
  LambdaQ.Abs.TApp term1 term2 -> failure x
  LambdaQ.Abs.TIfEl term1 term2 term3 -> failure x
  LambdaQ.Abs.TLet letvariable letvariables term1 term2 -> failure x
  LambdaQ.Abs.TCase term1 var1 term2 var2 term3 -> failure x
  LambdaQ.Abs.TLmbd lambda funvariable type_ term -> failure x
  LambdaQ.Abs.TDollr term1 term2 -> failure x

transArg :: LambdaQ.Abs.Arg -> Result
transArg x = case x of
  LambdaQ.Abs.FunArg var -> failure x

transFunction :: LambdaQ.Abs.Function -> Result
transFunction x = case x of
  LambdaQ.Abs.FunDef var args term -> failure x

transFunDeclaration :: LambdaQ.Abs.FunDeclaration -> Result
transFunDeclaration x = case x of
  LambdaQ.Abs.FunDecl funvariable type_ function -> failure x

transProgram :: LambdaQ.Abs.Program -> Result
transProgram x = case x of
  LambdaQ.Abs.ProgDef fundeclarations -> failure x
